### ISSUE TITLE
Cannot find next version.

### ISSUE THREAD

**Issue by Nek0-hinata** [haya14busa/action-bumpr#44]
here is the [PR](https://github.com/Nek0-hinata/projectS/pull/66)
![image](https://github.com/haya14busa/action-bumpr/assets/81868415/076e0d0f-9f93-4eec-a33d-15e4e41226e1)

core code:
```
name: Bump
on:
  push:
    # Use push on master event to run workflow instead of pull_request
    # closed (merged) event because github token doesn't have write permission
    # for pull_request from fork repository.
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    types:
      - labeled

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  release:
    if: github.event.action != 'labeled'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Bump version on merging Pull Requests with specific labels.
      # (bump:major,bump:minor,bump:patch)
      - id: bumpr
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: haya14busa/action-bumpr@v1

      # Update corresponding major and minor tag.
      # e.g. Update v1 and v1.2 when releasing v1.2.3
      - uses: haya14busa/action-update-semver@v1
        if: '!steps.bumpr.outputs.skip'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.bumpr.outputs.next_version }}

  release-check:
    if: github.event.action == 'labeled'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Post bumpr status comment
        uses: haya14busa/action-bumpr@v1
```
